import type { Metadata } from "next";
import { NavbarExample } from "@/components/nav/navbarExample";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarExample id={""}/>
        {children}
      </body>
    </html>
  );
}
