import type { Metadata } from "next";
import "./globals.css";
import { MenuExample } from "./components/blueprint/menuExample";


export const metadata: Metadata = {
  title: "Build UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
