import type { Metadata } from "next";
import { NavbarExample } from "./navbarExample";
import "./globals.css";

export const metadata: Metadata = {
  title: "Builder UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarExample id={""}/>
        {children}
      </body>
    </html>
  );
}
